
# Docker file to couple frontend, backend, and MySQL database instance into one.

version: "3.3"

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ThisIsNotAGoodPassword
    volumes:
      - database:/var/lib/mysql

  backend:
    image: servergardens/magic-backend:latest
    depends_on:
      - db
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - etc_magic_folder:/magic/files/etc
      - modules_magic_folder:/magic/files/modules
      - config_magic_folder:/magic/config

  frontend:
    image: servergardens/magic-frontend:latest
    depends_on:
      - backend
    restart: always
    ports:
      - "5555:80"

volumes:
  database:
  etc_magic_folder:
  modules_magic_folder:
  config_magic_folder:
