
# Docker file to couple frontend, backend, and MySQL database instance into one.

version: "3.9"

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ThisIsNotAGoodPassword
    volumes:
      - database:/var/lib/mysql

  backend:
    image: servergardens/magic-backend:latest
    depends_on:
      - db
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - files:/files
      - settings:/appsettings.json

  frontend:
    image: servergardens/magic-frontend:latest
    depends_on:
      - backend
    restart: always

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'magic.servergardens.com'
      SITES: 'magic.servergardens.com=frontend:80'

volumes:
  database:
  files:
  settings: 
  ssl_data: 
