
# Docker file to couple frontend, backend, and MySQL database instance into one.

version: "3.3"

services:

  db:
    image: mysql
    container_name: magic_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ThisIsNotAGoodPassword
    volumes:
      - database_mysql:/var/lib/mysql

  backend:
    image: servergardens/magic-backend:latest
    container_name: magic_backend
    depends_on:
      - db
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - magic_files_mysql:/magic/files

  frontend:
    image: servergardens/magic-frontend:latest
    container_name: magic_frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "5555:80"

volumes:
  database_mysql:
  magic_files_mysql:
