
# Docker file to couple frontend, backend, and MySQL database instance into one.

version: "3.3"

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ThisIsNotAGoodPassword
    volumes:
      - database:/var/lib/mysql

  backend:
    image: magic-backend:test
    depends_on:
      - db
    restart: always
    ports:
      - "4444:4444"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    image: magic-frontend:test
    depends_on:
      - backend
    restart: always
    ports:
      - "5555:80"

volumes:
  database:
