
# Notice, this file depends upon the ".env" file which pulls in the main docker-compose.yml file for Magic.
version: "2"

services:

  # Your app's main container
  [[name-lowers]]:
    container_name: [[name-lowers]]
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:

      # REPLACE THESE NEXT 3 PARTS WITH YOUR OWN DOMAIN/EMAIL
      - VIRTUAL_HOST=[[frontendUrl]]
      - LETSENCRYPT_HOST=[[frontendUrl]]
      - LETSENCRYPT_EMAIL=[[email]]

    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
