
# Builds and deploys Docker image

name: Docker Image CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push backend Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        cd ./frontend
        docker build -t servergardens/magic-frontend:latest-ci -f ./Dockerfile .
        docker push servergardens/magic-frontend:latest-ci
        cd ..
        cd ./backend
        docker build -t servergardens/magic-backend:latest-ci -f ./Dockerfile .
        docker push servergardens/magic-backend:latest-ci

    - name: Updating Docker images on DEV VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd magic.deploy
          docker-compose down
          docker pull servergardens/magic-frontend:latest-ci
          docker pull servergardens/magic-backend:latest-ci
          docker-compose up -d