
# This workflow builds the Dockerfiles for backend and frontend, publish these to Docker HUB,
# for then to trigger deployment on DEV server.
name: "Continous integration"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build frontend
      uses: ryanjfrizzell/action-bpd@master
      with:
        docker_registry_url: 'docker.pkg.github.com'
        docker_registry_owner: 'polterguy'
        docker_repository: 'magic'
        docker_image: 'magic-frontend'
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
        dockerfile: 'frontend/Dockerfile'
