
# Builds and deploys Docker image

name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      run: > 
        docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
        cd ./frontend;
        docker build --tag magic-frontend:latest-ci;
        docker push servergardens/magic-frontend:latest-ci;
        cd ../backend;
        docker build --tag magic-backend:latest-ci;
        docker push servergardens/magic-backend:latest-ci;
