
# Builds and deploys Docker image to DEV server

name: CI and CD for development environment
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker CI images backend/frontend
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        cd ./frontend
        docker build -t aistamagic/magic-frontend:latest-ci -f ./Dockerfile .
        docker push aistamagic/magic-frontend:latest-ci
        cd ..
        cd ./backend
        docker build -t aistamagic/magic-backend:latest-ci -f ./Dockerfile .
        docker push aistamagic/magic-backend:latest-ci
        dotnet remove reference magic.lambda.system
        dotnet remove reference magic.data.cql
        dotnet remove reference magic.lambda.cql
        docker build -t aistamagic/magic-backend:min-latest-ci -f ./Dockerfile .
        docker push aistamagic/magic-backend:min-latest-ci

    - name: Updating Docker images on DEV machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd magic.deploy
          docker-compose down
          docker pull aistamagic/magic-frontend:latest-ci
          docker pull aistamagic/magic-backend:latest-ci
          docker-compose up -d